### PR TITLE
Fixes/editable author

### LINKED ISSUE #26: Editing a post author's add tag to the post but doesn't link the author to the post
**Describe the bug**
When editing a post, when changing the author name, or adding one, the tag corresponding to the author is added to the posts, but the property author isn't set for the post

**To Reproduce**
If applicable, steps to reproduce the behavior:
1. Go to a post page and click "Edit"
2. Change the author name to another existing one
3. Validate
4. The posts will have the author tag listed but the author field is displayed as unkown

**Expected behavior**
Author field should be displaying author name and link

### PR DESCRIPTION
**Pull request by eternialz**
Fixes #26, and another issue where updating an author with an empty name removed main_alias from it's tag. 
Also improve author validation.

### CODE REVIEW

File: app/models/author.rb [hunk 1]
```diff
@@ -17,4 +17,6 @@ class Author < ApplicationRecord
     validates :tag, presence: true
     validates :name, presence: true
 
+    validates :website, allow_blank: true, format: { with: URI::DEFAULT_PARSER.make_regexp, message: 'You provided an invalid website URL.' }
```
Comment (Aruisehu) [inline app/models/author.rb]: Nice :+1:
